# Generated by Django 5.2.1 on 2025-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_column='nickname', default='temp_nickname', max_length=30),
            preserve_default=False,
        ),
    ]
