# Generated by Django 5.2.1 on 2025-05-28 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(db_column='comment_id', primary_key=True, serialize=False)),
                ('post_type', models.CharField(blank=True, choices=[('post', 'post'), ('group_post', 'group_post')], db_column='post_type', max_length=10, null=True)),
                ('post_id', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField(db_column='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'indexes': [models.Index(fields=['post_type', 'post_id'], name='comments_post_ty_2356b6_idx')],
            },
        ),
    ]
