# Generated by Django 5.2.1 on 2025-05-28 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('gpost_id', models.BigAutoField(db_column='gpost_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=150)),
                ('content', models.TextField(db_column='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='groups.group')),
            ],
            options={
                'db_table': 'group_posts',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(db_column='post_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=150)),
                ('content', models.TextField(db_column='content')),
                ('category', models.CharField(blank=True, db_column='category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='groups.group')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
