# Generated by Django 5.2.1 on 2025-05-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.BigAutoField(db_column='room_id', primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, db_column='room_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='groups.group')),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.BigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('message_text', models.TextField(db_column='message_text')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='sent_at')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
